name: Python application

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v7
      with:
        python-version: '3.14'
    - name: run test
      run: python -m unittest -v test_uint.py test_sint.py
